provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  llm:
    lang: python3-flask-debian
    handler: ./function
    image: localhost:5000/llm:latest
    min_replicas: 1
    build_args:
      ADDITIONAL_PACKAGE: ""
    environment:
      DIAGNOSTICS: "false"
      OFFLINE_MODEL_NAME: "/models/mistral-7b-instruct-v0.1.Q4_0.gguf"
      OFFLINE_MODEL_URL: "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_0.gguf"
      

